---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# scored

<!-- badges: start -->
<!-- badges: end -->

An R package to calculate similarity scores between cartridge cases based on the breech face impressions.

## Installation

You can install the development version of scored from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("jzemmels/scored")
```

## Example

This is a basic example which shows you how to solve a common problem:

```{r example,warning=FALSE,message=FALSE}
library(scored)

library(cmcR)
library(tidyverse)

data("K013sA1")
data("K013sA2")
```


```{r}
comparisonData <- comparison_cellBased(reference = K013sA1,target = K013sA2,
                                       thetas = seq(-30,30,by = 3),
                                       returnX3Ps = FALSE)

comparisonData
```

```{r}
comparisonData %>%
  feature_densityBasedAll(eps = 5,minPts = 5)
```

